const columns = [
    {name: "ID", uid: "id", sortable: true},
    {name: "NAME", uid: "name", sortable: true},
    {name: "MARKETCAP", uid: "market_cap", sortable: true},
    {name: "PRICE", uid: "price", sortable: true},
    {name: "TODAY", uid: "today", sortable: true},
    {name: "COUNTRY", uid: "country", sortable: true},
  ];
  
const statusOptions = [
    {name: "Active", uid: "active"},
    {name: "Paused", uid: "paused"},
    {name: "Vacation", uid: "vacation"},
  ];
  
const market_caps = [
      {"id":1,"name":"Jabbersphere","market_cap":"$493.06M","price":"$4435.57","today":41,"country":"Afghanistan"},
      {"id":2,"name":"Gigazoom","market_cap":"$2.78B","price":"$2524.16","today":87,"country":"Afghanistan"},
      {"id":3,"name":"Avamba","market_cap":"$2.4B","price":"$6810.35","today":42,"country":"Afghanistan"},
      {"id":4,"name":"Flashdog","market_cap":"$119.57M","price":"$7682.77","today":72,"country":"Afghanistan"},
      {"id":5,"name":"Meevee","market_cap":"$626.7M","price":"$7456.18","today":62,"country":"Afghanistan"},
      {"id":6,"name":"Feednation","market_cap":"$32.45M","price":"$1018.20","today":67,"country":"Afghanistan"},
      {"id":7,"name":"Aibox","market_cap":"$1.6B","price":"$3091.06","today":53,"country":"Afghanistan"},
      {"id":8,"name":"Geba","market_cap":"$371.14M","price":"$8719.00","today":39,"country":"Afghanistan"},
      {"id":9,"name":"Vitz","market_cap":"$208.46M","price":"$1379.39","today":32,"country":"Afghanistan"},
      {"id":10,"name":"Dynabox","market_cap":"$185.4M","price":"$459.61","today":52,"country":"Afghanistan"},
      {"id":11,"name":"Mydo","market_cap":"$6.65B","price":"$7118.24","today":49,"country":"Afghanistan"},
      {"id":12,"name":"Voonder","market_cap":"$955.69M","price":"$1229.86","today":66,"country":"Afghanistan"},
      {"id":13,"name":"Fadeo","market_cap":"$814.69M","price":"$4803.52","today":71,"country":"Afghanistan"},
      {"id":14,"name":"Aimbo","market_cap":"$61.61M","price":"$6104.09","today":30,"country":"Afghanistan"},
      {"id":15,"name":"Voonte","market_cap":"$49.95B","price":"$1625.25","today":72,"country":"Afghanistan"},
      {"id":16,"name":"Jaxworks","market_cap":"$14.65M","price":"$6088.33","today":73,"country":"Afghanistan"},
      {"id":17,"name":"Feedspan","market_cap":"$138.19M","price":"$3302.57","today":91,"country":"Afghanistan"},
      {"id":18,"name":"Tagtune","market_cap":"$14.6B","price":"$2340.18","today":41,"country":"Afghanistan"},
      {"id":19,"name":"Innojam","market_cap":"$14.34B","price":"$226.64","today":97,"country":"Afghanistan"},
      {"id":20,"name":"Chatterpoint","market_cap":"n/a","price":"$8062.84","today":16,"country":"Afghanistan"},
      {"id":21,"name":"Flashpoint","market_cap":"$7.13B","price":"$7009.10","today":10,"country":"Afghanistan"},
      {"id":22,"name":"Flashspan","market_cap":"$7.81B","price":"$5983.38","today":41,"country":"Afghanistan"},
      {"id":23,"name":"Youopia","market_cap":"$3.17B","price":"$3886.50","today":98,"country":"Afghanistan"},
      {"id":24,"name":"Devify","market_cap":"$6.7M","price":"$7018.19","today":15,"country":"Afghanistan"},
      {"id":25,"name":"Reallinks","market_cap":"$6.4B","price":"$2996.95","today":67,"country":"Afghanistan"},
      {"id":26,"name":"Thoughtblab","market_cap":"$132.8M","price":"$4667.64","today":33,"country":"Afghanistan"},
      {"id":27,"name":"Thoughtstorm","market_cap":"$763.03M","price":"$4690.27","today":3,"country":"Afghanistan"},
      {"id":28,"name":"Jabbertype","market_cap":"$79.48M","price":"$6985.79","today":63,"country":"Afghanistan"},
      {"id":29,"name":"Leexo","market_cap":"n/a","price":"$7417.98","today":100,"country":"Afghanistan"},
      {"id":30,"name":"Thoughtblab","market_cap":"$1.6B","price":"$7549.74","today":5,"country":"Afghanistan"},
      {"id":31,"name":"Oyope","market_cap":"$757.13M","price":"$2586.12","today":2,"country":"Afghanistan"},
      {"id":32,"name":"Ainyx","market_cap":"$5.39B","price":"$1574.81","today":79,"country":"Afghanistan"},
      {"id":33,"name":"Fivebridge","market_cap":"$1.06B","price":"$7711.56","today":37,"country":"Afghanistan"},
      {"id":34,"name":"Babblestorm","market_cap":"$37.85M","price":"$9566.17","today":6,"country":"Afghanistan"},
      {"id":35,"name":"Dabtype","market_cap":"$162.72M","price":"$416.68","today":22,"country":"Afghanistan"},
      {"id":36,"name":"Skinder","market_cap":"$2.17B","price":"$4179.91","today":87,"country":"Afghanistan"},
      {"id":37,"name":"Zoonoodle","market_cap":"$5.97B","price":"$6813.39","today":16,"country":"Afghanistan"},
      {"id":38,"name":"Gabvine","market_cap":"$21.06B","price":"$8634.21","today":49,"country":"Afghanistan"},
      {"id":39,"name":"Skimia","market_cap":"$220.5M","price":"$4329.77","today":67,"country":"Afghanistan"},
      {"id":40,"name":"Skippad","market_cap":"$113.2M","price":"$9844.90","today":26,"country":"Afghanistan"},
      {"id":41,"name":"Shuffledrive","market_cap":"n/a","price":"$775.19","today":26,"country":"Afghanistan"},
      {"id":42,"name":"Quimba","market_cap":"$90.19M","price":"$654.63","today":87,"country":"Afghanistan"},
      {"id":43,"name":"Dynava","market_cap":"$39.59B","price":"$905.39","today":55,"country":"Afghanistan"},
      {"id":44,"name":"Skipfire","market_cap":"n/a","price":"$7697.60","today":15,"country":"Afghanistan"},
      {"id":45,"name":"Gabcube","market_cap":"$642.98M","price":"$5134.66","today":36,"country":"Afghanistan"},
      {"id":46,"name":"Thoughtbridge","market_cap":"$1.53B","price":"$808.06","today":46,"country":"Afghanistan"},
      {"id":47,"name":"Blogspan","market_cap":"$107.46M","price":"$2257.64","today":75,"country":"Afghanistan"},
      {"id":48,"name":"Demivee","market_cap":"n/a","price":"$8618.87","today":11,"country":"Afghanistan"},
      {"id":49,"name":"Zoomcast","market_cap":"$264.23M","price":"$650.29","today":13,"country":"Afghanistan"},
      {"id":50,"name":"Brainlounge","market_cap":"$3.66B","price":"$9501.62","today":5,"country":"Afghanistan"},
      {"id":51,"name":"Katz","market_cap":"$100.44M","price":"$5490.91","today":90,"country":"Afghanistan"},
      {"id":52,"name":"Zoonoodle","market_cap":"$175.49M","price":"$7156.22","today":33,"country":"Afghanistan"},
      {"id":53,"name":"Twinder","market_cap":"n/a","price":"$5994.70","today":11,"country":"Afghanistan"},
      {"id":54,"name":"Rhyloo","market_cap":"$5.24B","price":"$3261.63","today":61,"country":"Afghanistan"},
      {"id":55,"name":"Camimbo","market_cap":"$1.1B","price":"$8871.76","today":75,"country":"Afghanistan"},
      {"id":56,"name":"Wordify","market_cap":"$84.39M","price":"$9791.45","today":87,"country":"Afghanistan"},
      {"id":57,"name":"InnoZ","market_cap":"$87.88M","price":"$9833.80","today":26,"country":"Afghanistan"},
      {"id":58,"name":"Nlounge","market_cap":"$184.04M","price":"$9862.18","today":35,"country":"Afghanistan"},
      {"id":59,"name":"Yamia","market_cap":"$14.78B","price":"$6943.10","today":86,"country":"Afghanistan"},
      {"id":60,"name":"Skipfire","market_cap":"n/a","price":"$9091.94","today":93,"country":"Afghanistan"},
      {"id":61,"name":"Wordpedia","market_cap":"$76.6B","price":"$1568.00","today":31,"country":"Afghanistan"},
      {"id":62,"name":"Abata","market_cap":"$4.01B","price":"$6449.24","today":78,"country":"Afghanistan"},
      {"id":63,"name":"Skimia","market_cap":"$1.12B","price":"$3981.56","today":67,"country":"Afghanistan"},
      {"id":64,"name":"Flashpoint","market_cap":"$96.77M","price":"$2983.13","today":81,"country":"Afghanistan"},
      {"id":65,"name":"DabZ","market_cap":"$485.31M","price":"$7396.84","today":31,"country":"Afghanistan"},
      {"id":66,"name":"Dabvine","market_cap":"$24.27B","price":"$6674.95","today":79,"country":"Afghanistan"},
      {"id":67,"name":"Brainsphere","market_cap":"n/a","price":"$7063.47","today":75,"country":"Afghanistan"},
      {"id":68,"name":"Topicblab","market_cap":"$14.14B","price":"$1610.09","today":54,"country":"Afghanistan"},
      {"id":69,"name":"Tagpad","market_cap":"$658.05M","price":"$1057.16","today":4,"country":"Afghanistan"},
      {"id":70,"name":"Voonix","market_cap":"$45.14B","price":"$5268.34","today":83,"country":"Afghanistan"},
      {"id":71,"name":"Jabberstorm","market_cap":"$581.4M","price":"$2024.31","today":41,"country":"Afghanistan"},
      {"id":72,"name":"Zoozzy","market_cap":"$21.61B","price":"$3178.52","today":100,"country":"Afghanistan"},
      {"id":73,"name":"Eazzy","market_cap":"$27.49M","price":"$3262.28","today":39,"country":"Afghanistan"},
      {"id":74,"name":"Centizu","market_cap":"$6.98B","price":"$8928.04","today":69,"country":"Afghanistan"},
      {"id":75,"name":"Yakitri","market_cap":"$858.82M","price":"$6420.93","today":13,"country":"Afghanistan"},
      {"id":76,"name":"Demimbu","market_cap":"$134.2M","price":"$7447.62","today":90,"country":"Afghanistan"},
      {"id":77,"name":"Fivebridge","market_cap":"$172.36M","price":"$346.46","today":33,"country":"Afghanistan"},
      {"id":78,"name":"Oyoloo","market_cap":"$117.69M","price":"$4071.01","today":89,"country":"Afghanistan"},
      {"id":79,"name":"Trunyx","market_cap":"$91.07M","price":"$7337.12","today":16,"country":"Afghanistan"},
      {"id":80,"name":"Yozio","market_cap":"$2.73B","price":"$5627.85","today":20,"country":"Afghanistan"},
      {"id":81,"name":"Topicstorm","market_cap":"$78.86M","price":"$1329.26","today":87,"country":"Afghanistan"},
      {"id":82,"name":"Jaxnation","market_cap":"$5.13B","price":"$5740.63","today":55,"country":"Afghanistan"},
      {"id":83,"name":"Quatz","market_cap":"$45.09M","price":"$4199.86","today":54,"country":"Afghanistan"},
      {"id":84,"name":"Rhynoodle","market_cap":"$101.69M","price":"$4204.65","today":65,"country":"Afghanistan"},
      {"id":85,"name":"Edgeclub","market_cap":"$9.64B","price":"$5335.58","today":98,"country":"Afghanistan"},
      {"id":86,"name":"Dynabox","market_cap":"$70.59M","price":"$7690.33","today":57,"country":"Afghanistan"},
      {"id":87,"name":"Ntag","market_cap":"$660.87M","price":"$185.00","today":74,"country":"Afghanistan"},
      {"id":88,"name":"Twimbo","market_cap":"$252.5M","price":"$3485.15","today":18,"country":"Afghanistan"},
      {"id":89,"name":"Zoonoodle","market_cap":"$705.42M","price":"$4399.87","today":66,"country":"Afghanistan"},
      {"id":90,"name":"Katz","market_cap":"n/a","price":"$6373.44","today":7,"country":"Afghanistan"},
      {"id":91,"name":"Skivee","market_cap":"$60.75M","price":"$1511.54","today":98,"country":"Afghanistan"},
      {"id":92,"name":"Twitterlist","market_cap":"$491.02M","price":"$403.58","today":47,"country":"Afghanistan"},
      {"id":93,"name":"Flipbug","market_cap":"$2.13B","price":"$2854.95","today":82,"country":"Afghanistan"},
      {"id":94,"name":"Yodo","market_cap":"n/a","price":"$2375.97","today":10,"country":"Afghanistan"},
      {"id":95,"name":"Fatz","market_cap":"n/a","price":"$3272.13","today":41,"country":"Afghanistan"},
      {"id":96,"name":"Blogspan","market_cap":"$33.71M","price":"$7795.49","today":98,"country":"Afghanistan"},
      {"id":97,"name":"Kamba","market_cap":"$220.68B","price":"$2040.83","today":72,"country":"Afghanistan"},
      {"id":98,"name":"Thoughtblab","market_cap":"$552.77M","price":"$1278.11","today":95,"country":"Afghanistan"},
      {"id":99,"name":"Dabjam","market_cap":"$34.26B","price":"$7328.63","today":24,"country":"Afghanistan"},
      {"id":100,"name":"Devpoint","market_cap":"$1.4B","price":"$8462.18","today":63,"country":"Afghanistan"},
      {"id":101,"name":"Flashspan","market_cap":"$92.34B","price":"$9087.26","today":80,"country":"Afghanistan"},
      {"id":102,"name":"Gabtune","market_cap":"$17.7B","price":"$4433.61","today":44,"country":"Afghanistan"},
      {"id":103,"name":"Oyoyo","market_cap":"$961.1M","price":"$8485.74","today":33,"country":"Afghanistan"},
      {"id":104,"name":"Thoughtbeat","market_cap":"$771.82M","price":"$1947.06","today":59,"country":"Afghanistan"},
      {"id":105,"name":"Skynoodle","market_cap":"n/a","price":"$9152.05","today":7,"country":"Afghanistan"},
      {"id":106,"name":"Babbleblab","market_cap":"$277.12M","price":"$5438.84","today":72,"country":"Afghanistan"},
      {"id":107,"name":"Pixoboo","market_cap":"$675.47M","price":"$2111.78","today":10,"country":"Afghanistan"},
      {"id":108,"name":"Photobug","market_cap":"$89.72B","price":"$5059.52","today":73,"country":"Afghanistan"},
      {"id":109,"name":"Cogibox","market_cap":"$431.87M","price":"$8687.62","today":28,"country":"Afghanistan"},
      {"id":110,"name":"Tagpad","market_cap":"n/a","price":"$9610.74","today":64,"country":"Afghanistan"},
      {"id":111,"name":"Buzzshare","market_cap":"$58.06M","price":"$2721.71","today":34,"country":"Afghanistan"},
      {"id":112,"name":"Meembee","market_cap":"$3.6B","price":"$583.24","today":72,"country":"Afghanistan"},
      {"id":113,"name":"Gabtype","market_cap":"$463.93M","price":"$4334.01","today":73,"country":"Afghanistan"},
      {"id":114,"name":"Youspan","market_cap":"$1.73B","price":"$7448.11","today":4,"country":"Afghanistan"},
      {"id":115,"name":"Realpoint","market_cap":"$146.29M","price":"$8835.54","today":67,"country":"Afghanistan"},
      {"id":116,"name":"Photobug","market_cap":"$8.51B","price":"$2552.42","today":35,"country":"Afghanistan"},
      {"id":117,"name":"Devshare","market_cap":"n/a","price":"$9789.85","today":10,"country":"Afghanistan"},
      {"id":118,"name":"Meejo","market_cap":"$1.28B","price":"$4052.51","today":33,"country":"Afghanistan"},
      {"id":119,"name":"Ooba","market_cap":"$10.54M","price":"$6903.27","today":98,"country":"Afghanistan"},
      {"id":120,"name":"Skippad","market_cap":"$4.76M","price":"$6403.14","today":66,"country":"Afghanistan"},
      {"id":121,"name":"Yakidoo","market_cap":"$6.05B","price":"$2493.87","today":91,"country":"Afghanistan"},
      {"id":122,"name":"Wikibox","market_cap":"$18.6M","price":"$3061.24","today":65,"country":"Afghanistan"},
      {"id":123,"name":"Blogspan","market_cap":"$4.13B","price":"$6328.82","today":40,"country":"Afghanistan"},
      {"id":124,"name":"Chatterpoint","market_cap":"$162.35M","price":"$302.22","today":39,"country":"Afghanistan"},
      {"id":125,"name":"Dabtype","market_cap":"$389.62M","price":"$1248.73","today":70,"country":"Afghanistan"},
      {"id":126,"name":"Wikido","market_cap":"n/a","price":"$6557.75","today":25,"country":"Afghanistan"},
      {"id":127,"name":"Yabox","market_cap":"$58.06M","price":"$6558.75","today":51,"country":"Afghanistan"},
      {"id":128,"name":"Gigazoom","market_cap":"n/a","price":"$7513.70","today":29,"country":"Afghanistan"},
      {"id":129,"name":"Edgeblab","market_cap":"$29.21B","price":"$3403.87","today":40,"country":"Afghanistan"},
      {"id":130,"name":"Dynazzy","market_cap":"$42.85M","price":"$2920.78","today":63,"country":"Afghanistan"},
      {"id":131,"name":"Wordware","market_cap":"$11.05B","price":"$8768.23","today":28,"country":"Afghanistan"},
      {"id":132,"name":"Gigashots","market_cap":"$30.65M","price":"$9224.12","today":97,"country":"Afghanistan"},
      {"id":133,"name":"Aimbu","market_cap":"n/a","price":"$5105.13","today":39,"country":"Afghanistan"},
      {"id":134,"name":"Aimbo","market_cap":"$20.66M","price":"$9519.30","today":32,"country":"Afghanistan"},
      {"id":135,"name":"Wikizz","market_cap":"n/a","price":"$1493.26","today":98,"country":"Afghanistan"},
      {"id":136,"name":"Photobug","market_cap":"$828.17M","price":"$8445.96","today":52,"country":"Afghanistan"},
      {"id":137,"name":"Talane","market_cap":"$1.74B","price":"$1771.11","today":38,"country":"Afghanistan"},
      {"id":138,"name":"Aimbo","market_cap":"$5.23B","price":"$7776.81","today":99,"country":"Afghanistan"},
      {"id":139,"name":"Feedmix","market_cap":"$3.4B","price":"$9565.20","today":52,"country":"Afghanistan"},
      {"id":140,"name":"Chatterbridge","market_cap":"$3.73B","price":"$1479.92","today":83,"country":"Afghanistan"},
      {"id":141,"name":"Feedfire","market_cap":"$1.04B","price":"$5078.88","today":63,"country":"Afghanistan"},
      {"id":142,"name":"Eayo","market_cap":"$2.53B","price":"$694.74","today":52,"country":"Afghanistan"},
      {"id":143,"name":"Oyondu","market_cap":"$333.24M","price":"$7173.47","today":92,"country":"Afghanistan"},
      {"id":144,"name":"Vipe","market_cap":"$12.86B","price":"$5602.30","today":36,"country":"Afghanistan"},
      {"id":145,"name":"Gigazoom","market_cap":"n/a","price":"$9745.40","today":69,"country":"Afghanistan"},
      {"id":146,"name":"Feedfish","market_cap":"$2.27B","price":"$6482.20","today":72,"country":"Afghanistan"},
      {"id":147,"name":"Edgewire","market_cap":"$49.22M","price":"$8059.10","today":16,"country":"Afghanistan"},
      {"id":148,"name":"Dynava","market_cap":"$384.22M","price":"$3092.63","today":34,"country":"Afghanistan"},
      {"id":149,"name":"Aivee","market_cap":"$8.25B","price":"$1419.18","today":18,"country":"Afghanistan"},
      {"id":150,"name":"Riffpedia","market_cap":"$3.55B","price":"$8562.01","today":97,"country":"Afghanistan"},
      {"id":151,"name":"Mymm","market_cap":"$3.4B","price":"$2854.49","today":28,"country":"Afghanistan"},
      {"id":152,"name":"Browseblab","market_cap":"n/a","price":"$220.00","today":35,"country":"Afghanistan"},
      {"id":153,"name":"Jetwire","market_cap":"n/a","price":"$3477.24","today":90,"country":"Afghanistan"},
      {"id":154,"name":"Dynava","market_cap":"$4.59B","price":"$7134.56","today":15,"country":"Afghanistan"},
      {"id":155,"name":"Skiptube","market_cap":"n/a","price":"$8341.33","today":7,"country":"Afghanistan"},
      {"id":156,"name":"Youbridge","market_cap":"$556.34M","price":"$7170.90","today":5,"country":"Afghanistan"},
      {"id":157,"name":"Meedoo","market_cap":"$56.73M","price":"$4216.32","today":23,"country":"Afghanistan"},
      {"id":158,"name":"Blogspan","market_cap":"$2.48B","price":"$479.33","today":83,"country":"Afghanistan"},
      {"id":159,"name":"Riffwire","market_cap":"$137.3M","price":"$3116.02","today":58,"country":"Afghanistan"},
      {"id":160,"name":"Izio","market_cap":"$1.8B","price":"$4077.64","today":3,"country":"Afghanistan"},
      {"id":161,"name":"Kazio","market_cap":"n/a","price":"$3331.26","today":46,"country":"Afghanistan"},
      {"id":162,"name":"Gabtune","market_cap":"$54.22B","price":"$1398.01","today":42,"country":"Afghanistan"},
      {"id":163,"name":"Einti","market_cap":"$10.74B","price":"$2016.08","today":16,"country":"Afghanistan"},
      {"id":164,"name":"Oozz","market_cap":"$39.11B","price":"$1351.25","today":1,"country":"Afghanistan"},
      {"id":165,"name":"Innojam","market_cap":"$205.28B","price":"$7729.34","today":83,"country":"Afghanistan"},
      {"id":166,"name":"Tagfeed","market_cap":"n/a","price":"$1155.97","today":58,"country":"Afghanistan"},
      {"id":167,"name":"Brainsphere","market_cap":"$885.83M","price":"$1630.23","today":60,"country":"Afghanistan"},
      {"id":168,"name":"Livefish","market_cap":"$669.59M","price":"$1769.85","today":42,"country":"Afghanistan"},
      {"id":169,"name":"Yozio","market_cap":"$20.2B","price":"$4363.72","today":36,"country":"Afghanistan"},
      {"id":170,"name":"Bluejam","market_cap":"$5.28B","price":"$4938.45","today":77,"country":"Afghanistan"},
      {"id":171,"name":"Voomm","market_cap":"$140.84M","price":"$7494.19","today":50,"country":"Afghanistan"},
      {"id":172,"name":"Jabbersphere","market_cap":"n/a","price":"$3425.44","today":79,"country":"Afghanistan"},
      {"id":173,"name":"Edgeify","market_cap":"$387.37M","price":"$579.18","today":72,"country":"Afghanistan"},
      {"id":174,"name":"Meevee","market_cap":"n/a","price":"$2530.63","today":77,"country":"Afghanistan"},
      {"id":175,"name":"Realcube","market_cap":"$252.54M","price":"$9412.20","today":54,"country":"Afghanistan"},
      {"id":176,"name":"Fivebridge","market_cap":"$136.89M","price":"$490.91","today":7,"country":"Afghanistan"},
      {"id":177,"name":"Miboo","market_cap":"$332.19M","price":"$1697.14","today":45,"country":"Afghanistan"},
      {"id":178,"name":"Bubbletube","market_cap":"$1.35B","price":"$5071.51","today":5,"country":"Afghanistan"},
      {"id":179,"name":"Tagfeed","market_cap":"$90.21B","price":"$1468.47","today":35,"country":"Afghanistan"},
      {"id":180,"name":"Meezzy","market_cap":"$59.88M","price":"$9130.47","today":63,"country":"Afghanistan"},
      {"id":181,"name":"Zoombeat","market_cap":"$4.9B","price":"$914.42","today":48,"country":"Afghanistan"},
      {"id":182,"name":"Brainbox","market_cap":"$480.35M","price":"$5234.16","today":43,"country":"Afghanistan"},
      {"id":183,"name":"Rhyloo","market_cap":"n/a","price":"$9573.10","today":4,"country":"Afghanistan"},
      {"id":184,"name":"Fivebridge","market_cap":"$22.73M","price":"$1351.86","today":71,"country":"Afghanistan"},
      {"id":185,"name":"Voolia","market_cap":"$618.24M","price":"$3694.82","today":75,"country":"Afghanistan"},
      {"id":186,"name":"Gigazoom","market_cap":"$392729.7","price":"$6290.69","today":70,"country":"Afghanistan"},
      {"id":187,"name":"Photobean","market_cap":"$322.34M","price":"$2163.14","today":7,"country":"Afghanistan"},
      {"id":188,"name":"Topicware","market_cap":"$130.45M","price":"$9935.69","today":63,"country":"Afghanistan"},
      {"id":189,"name":"Wordware","market_cap":"$4.13B","price":"$8432.92","today":66,"country":"Afghanistan"},
      {"id":190,"name":"Pixoboo","market_cap":"$2.02B","price":"$2834.91","today":45,"country":"Afghanistan"},
      {"id":191,"name":"Twiyo","market_cap":"n/a","price":"$6675.09","today":76,"country":"Afghanistan"},
      {"id":192,"name":"Skalith","market_cap":"n/a","price":"$2112.88","today":38,"country":"Afghanistan"},
      {"id":193,"name":"Quatz","market_cap":"$445.08M","price":"$246.08","today":85,"country":"Afghanistan"},
      {"id":194,"name":"Fivebridge","market_cap":"$556.53M","price":"$9192.94","today":33,"country":"Afghanistan"},
      {"id":195,"name":"LiveZ","market_cap":"n/a","price":"$1479.37","today":20,"country":"Afghanistan"},
      {"id":196,"name":"Twimm","market_cap":"$165.8B","price":"$6834.69","today":36,"country":"Afghanistan"},
      {"id":197,"name":"Wikido","market_cap":"$2.45B","price":"$2177.51","today":52,"country":"Afghanistan"},
      {"id":198,"name":"Oba","market_cap":"$107.75B","price":"$326.90","today":27,"country":"Afghanistan"},
      {"id":199,"name":"Podcat","market_cap":"n/a","price":"$2535.65","today":90,"country":"Afghanistan"},
      {"id":200,"name":"Chatterpoint","market_cap":"$1.12B","price":"$1467.21","today":7,"country":"Afghanistan"},
      {"id":201,"name":"Skipstorm","market_cap":"$1.51B","price":"$3148.68","today":86,"country":"Afghanistan"},
      {"id":202,"name":"Realcube","market_cap":"$323.02M","price":"$2871.80","today":88,"country":"Afghanistan"},
      {"id":203,"name":"JumpXS","market_cap":"$1.66B","price":"$5475.76","today":72,"country":"Afghanistan"},
      {"id":204,"name":"Flashdog","market_cap":"$1.03B","price":"$5690.73","today":69,"country":"Afghanistan"},
      {"id":205,"name":"Skipfire","market_cap":"$3.72B","price":"$5522.63","today":73,"country":"Afghanistan"},
      {"id":206,"name":"Dazzlesphere","market_cap":"$317.19M","price":"$4963.44","today":54,"country":"Afghanistan"},
      {"id":207,"name":"Zoomcast","market_cap":"n/a","price":"$9495.12","today":99,"country":"Afghanistan"},
      {"id":208,"name":"Blogtag","market_cap":"$283.57M","price":"$6006.93","today":23,"country":"Afghanistan"},
      {"id":209,"name":"Browsetype","market_cap":"$1.63B","price":"$3845.90","today":96,"country":"Afghanistan"},
      {"id":210,"name":"Skyvu","market_cap":"$95.4M","price":"$6681.05","today":46,"country":"Afghanistan"},
      {"id":211,"name":"Linktype","market_cap":"$69.13M","price":"$8859.07","today":6,"country":"Afghanistan"},
      {"id":212,"name":"Tazzy","market_cap":"n/a","price":"$392.24","today":78,"country":"Afghanistan"},
      {"id":213,"name":"Avamba","market_cap":"$581.4M","price":"$3534.04","today":99,"country":"Afghanistan"},
      {"id":214,"name":"Thoughtstorm","market_cap":"$177.78M","price":"$782.60","today":59,"country":"Afghanistan"},
      {"id":215,"name":"Vitz","market_cap":"$10.91B","price":"$8395.98","today":46,"country":"Afghanistan"},
      {"id":216,"name":"Avamba","market_cap":"$2.09B","price":"$420.12","today":84,"country":"Afghanistan"},
      {"id":217,"name":"Kanoodle","market_cap":"$795.23M","price":"$527.43","today":36,"country":"Afghanistan"},
      {"id":218,"name":"Twitterwire","market_cap":"$14.64B","price":"$5386.06","today":25,"country":"Afghanistan"},
      {"id":219,"name":"Divanoodle","market_cap":"$93.02M","price":"$2685.94","today":43,"country":"Afghanistan"},
      {"id":220,"name":"Jaxworks","market_cap":"$1.15B","price":"$968.57","today":20,"country":"Afghanistan"},
      {"id":221,"name":"Zoozzy","market_cap":"$78.67B","price":"$7740.46","today":63,"country":"Afghanistan"},
      {"id":222,"name":"Zava","market_cap":"$684.03M","price":"$5104.84","today":76,"country":"Afghanistan"},
      {"id":223,"name":"Realfire","market_cap":"$562.64M","price":"$5971.40","today":36,"country":"Afghanistan"},
      {"id":224,"name":"Skyvu","market_cap":"$94.88B","price":"$684.27","today":81,"country":"Afghanistan"},
      {"id":225,"name":"Meevee","market_cap":"$21.6M","price":"$1744.26","today":96,"country":"Afghanistan"},
      {"id":226,"name":"Jamia","market_cap":"$89.72B","price":"$1595.80","today":36,"country":"Afghanistan"},
      {"id":227,"name":"Topicware","market_cap":"$1.9B","price":"$8475.98","today":98,"country":"Afghanistan"},
      {"id":228,"name":"Tanoodle","market_cap":"$3.62B","price":"$8333.76","today":74,"country":"Afghanistan"},
      {"id":229,"name":"Ainyx","market_cap":"$2.58B","price":"$796.96","today":14,"country":"Afghanistan"},
      {"id":230,"name":"Photolist","market_cap":"$58.13M","price":"$3586.66","today":82,"country":"Afghanistan"},
      {"id":231,"name":"Yata","market_cap":"$2.09B","price":"$2598.38","today":78,"country":"Afghanistan"},
      {"id":232,"name":"Demivee","market_cap":"n/a","price":"$1466.84","today":32,"country":"Afghanistan"},
      {"id":233,"name":"Skalith","market_cap":"n/a","price":"$694.58","today":89,"country":"Afghanistan"},
      {"id":234,"name":"Twinte","market_cap":"$165.71M","price":"$5429.93","today":89,"country":"Afghanistan"},
      {"id":235,"name":"Pixonyx","market_cap":"$236.5M","price":"$6849.22","today":16,"country":"Afghanistan"},
      {"id":236,"name":"Thoughtworks","market_cap":"$306.09M","price":"$9015.03","today":20,"country":"Afghanistan"},
      {"id":237,"name":"Thoughtstorm","market_cap":"$90.19M","price":"$359.35","today":83,"country":"Afghanistan"},
      {"id":238,"name":"Blogtag","market_cap":"$28.13M","price":"$9540.39","today":63,"country":"Afghanistan"},
      {"id":239,"name":"Janyx","market_cap":"$446.85M","price":"$8808.36","today":13,"country":"Afghanistan"},
      {"id":240,"name":"Pixoboo","market_cap":"$6.55B","price":"$9951.53","today":25,"country":"Afghanistan"},
      {"id":241,"name":"Mynte","market_cap":"$441.75M","price":"$4605.34","today":83,"country":"Afghanistan"},
      {"id":242,"name":"Voonte","market_cap":"$755.36M","price":"$9580.61","today":73,"country":"Afghanistan"},
      {"id":243,"name":"Kazio","market_cap":"$22.56B","price":"$4994.56","today":27,"country":"Afghanistan"},
      {"id":244,"name":"Meejo","market_cap":"n/a","price":"$6930.06","today":38,"country":"Afghanistan"},
      {"id":245,"name":"Ntags","market_cap":"n/a","price":"$3743.46","today":26,"country":"Afghanistan"},
      {"id":246,"name":"Fivechat","market_cap":"$2.87B","price":"$8967.54","today":60,"country":"Afghanistan"},
      {"id":247,"name":"Vinder","market_cap":"$56.32M","price":"$7294.70","today":17,"country":"Afghanistan"},
      {"id":248,"name":"Thoughtstorm","market_cap":"$6.97B","price":"$8486.87","today":7,"country":"Afghanistan"},
      {"id":249,"name":"Feedspan","market_cap":"$436.6M","price":"$2366.70","today":29,"country":"Afghanistan"},
      {"id":250,"name":"Eimbee","market_cap":"$145.98B","price":"$3439.47","today":35,"country":"Afghanistan"},
      {"id":251,"name":"Plajo","market_cap":"$1.64B","price":"$9989.12","today":74,"country":"Afghanistan"},
      {"id":252,"name":"Eabox","market_cap":"$99.4M","price":"$9430.26","today":68,"country":"Afghanistan"},
      {"id":253,"name":"Zazio","market_cap":"$476.74M","price":"$7043.30","today":73,"country":"Afghanistan"},
      {"id":254,"name":"Skibox","market_cap":"n/a","price":"$6461.19","today":92,"country":"Afghanistan"},
      {"id":255,"name":"Eazzy","market_cap":"$414.73M","price":"$7679.07","today":35,"country":"Afghanistan"},
      {"id":256,"name":"Skidoo","market_cap":"$3.82B","price":"$8296.19","today":16,"country":"Afghanistan"},
      {"id":257,"name":"Jabbersphere","market_cap":"$7.76B","price":"$6365.23","today":28,"country":"Afghanistan"},
      {"id":258,"name":"Babblestorm","market_cap":"n/a","price":"$451.57","today":94,"country":"Afghanistan"},
      {"id":259,"name":"Livepath","market_cap":"$120.08M","price":"$9307.20","today":6,"country":"Afghanistan"},
      {"id":260,"name":"Voolith","market_cap":"$750.72M","price":"$9380.34","today":26,"country":"Afghanistan"},
      {"id":261,"name":"Zoonoodle","market_cap":"$2.71B","price":"$3410.65","today":49,"country":"Afghanistan"},
      {"id":262,"name":"Vipe","market_cap":"n/a","price":"$4506.71","today":96,"country":"Afghanistan"},
      {"id":263,"name":"Brainverse","market_cap":"n/a","price":"$6956.50","today":43,"country":"Afghanistan"},
      {"id":264,"name":"Thoughtstorm","market_cap":"$15.33B","price":"$1233.69","today":64,"country":"Afghanistan"},
      {"id":265,"name":"Blogspan","market_cap":"$1.05B","price":"$3338.72","today":77,"country":"Afghanistan"},
      {"id":266,"name":"Viva","market_cap":"$36.08B","price":"$4000.43","today":41,"country":"Afghanistan"},
      {"id":267,"name":"Yakijo","market_cap":"$60.75M","price":"$9718.51","today":79,"country":"Afghanistan"},
      {"id":268,"name":"Skajo","market_cap":"$179.29M","price":"$9604.74","today":5,"country":"Afghanistan"},
      {"id":269,"name":"Thoughtsphere","market_cap":"$70.95M","price":"$5986.41","today":44,"country":"Afghanistan"},
      {"id":270,"name":"Tanoodle","market_cap":"$243.62M","price":"$5590.16","today":17,"country":"Afghanistan"},
      {"id":271,"name":"Linktype","market_cap":"$1.95B","price":"$1407.04","today":91,"country":"Afghanistan"},
      {"id":272,"name":"Browseblab","market_cap":"$121.9M","price":"$5189.97","today":87,"country":"Afghanistan"},
      {"id":273,"name":"Tagfeed","market_cap":"$38.27M","price":"$7103.46","today":1,"country":"Afghanistan"},
      {"id":274,"name":"Skiba","market_cap":"$1.1B","price":"$533.98","today":60,"country":"Afghanistan"},
      {"id":275,"name":"Dynabox","market_cap":"$1.43B","price":"$4255.50","today":99,"country":"Afghanistan"},
      {"id":276,"name":"Feedbug","market_cap":"n/a","price":"$9923.98","today":76,"country":"Afghanistan"},
      {"id":277,"name":"Eimbee","market_cap":"$65.99M","price":"$4615.22","today":45,"country":"Afghanistan"},
      {"id":278,"name":"Realfire","market_cap":"$8.56B","price":"$3906.17","today":41,"country":"Afghanistan"},
      {"id":279,"name":"Centimia","market_cap":"$747.14M","price":"$2816.53","today":72,"country":"Afghanistan"},
      {"id":280,"name":"Yodoo","market_cap":"$233.83M","price":"$1487.79","today":84,"country":"Afghanistan"},
      {"id":281,"name":"Jabberbean","market_cap":"$5.77B","price":"$3107.53","today":1,"country":"Afghanistan"},
      {"id":282,"name":"Skipfire","market_cap":"$23.56M","price":"$9882.75","today":82,"country":"Afghanistan"},
      {"id":283,"name":"Katz","market_cap":"$34.21M","price":"$1208.96","today":9,"country":"Afghanistan"},
      {"id":284,"name":"Realbuzz","market_cap":"$186.14M","price":"$7216.90","today":65,"country":"Afghanistan"},
      {"id":285,"name":"Feednation","market_cap":"n/a","price":"$4701.17","today":90,"country":"Afghanistan"},
      {"id":286,"name":"Abatz","market_cap":"n/a","price":"$287.73","today":21,"country":"Afghanistan"},
      {"id":287,"name":"Eadel","market_cap":"n/a","price":"$8474.79","today":10,"country":"Afghanistan"},
      {"id":288,"name":"Tagtune","market_cap":"$1.54B","price":"$8556.90","today":91,"country":"Afghanistan"},
      {"id":289,"name":"Twitterworks","market_cap":"$42.87B","price":"$2638.56","today":5,"country":"Afghanistan"},
      {"id":290,"name":"Skimia","market_cap":"n/a","price":"$707.82","today":19,"country":"Afghanistan"},
      {"id":291,"name":"Dabshots","market_cap":"$346.48M","price":"$9884.95","today":96,"country":"Afghanistan"},
      {"id":292,"name":"Kayveo","market_cap":"$2.57B","price":"$8370.94","today":50,"country":"Afghanistan"},
      {"id":293,"name":"Quinu","market_cap":"$3.61B","price":"$3923.37","today":32,"country":"Afghanistan"},
      {"id":294,"name":"Trilith","market_cap":"$4.23B","price":"$561.85","today":76,"country":"Afghanistan"},
      {"id":295,"name":"Yakijo","market_cap":"$1.48B","price":"$7544.15","today":3,"country":"Afghanistan"},
      {"id":296,"name":"Gigazoom","market_cap":"$106.14M","price":"$9896.18","today":44,"country":"Afghanistan"},
      {"id":297,"name":"Meevee","market_cap":"$13.93B","price":"$2488.77","today":38,"country":"Afghanistan"},
      {"id":298,"name":"Dynava","market_cap":"$158.53M","price":"$2548.12","today":87,"country":"Afghanistan"},
      {"id":299,"name":"Nlounge","market_cap":"n/a","price":"$4741.39","today":5,"country":"Afghanistan"},
      {"id":300,"name":"Skajo","market_cap":"$55.25M","price":"$9413.25","today":17,"country":"Afghanistan"},
      {"id":301,"name":"Skinder","market_cap":"n/a","price":"$2913.20","today":13,"country":"Afghanistan"},
      {"id":302,"name":"Twitterlist","market_cap":"$309.27M","price":"$1950.69","today":47,"country":"Afghanistan"},
      {"id":303,"name":"Lazz","market_cap":"$2.49B","price":"$1655.25","today":46,"country":"Afghanistan"},
      {"id":304,"name":"Dynabox","market_cap":"n/a","price":"$6587.12","today":17,"country":"Afghanistan"},
      {"id":305,"name":"Buzzster","market_cap":"$1.03B","price":"$6630.31","today":66,"country":"Afghanistan"},
      {"id":306,"name":"Skiba","market_cap":"$16.21B","price":"$7398.18","today":24,"country":"Afghanistan"},
      {"id":307,"name":"Camimbo","market_cap":"$108.87B","price":"$4574.78","today":44,"country":"Afghanistan"},
      {"id":308,"name":"Fivebridge","market_cap":"$4.58B","price":"$5377.15","today":78,"country":"Afghanistan"},
      {"id":309,"name":"Browsetype","market_cap":"$260.58M","price":"$4802.02","today":37,"country":"Afghanistan"},
      {"id":310,"name":"Dabjam","market_cap":"$224.11M","price":"$9857.11","today":15,"country":"Afghanistan"},
      {"id":311,"name":"Yamia","market_cap":"$21.39B","price":"$6016.72","today":91,"country":"Afghanistan"},
      {"id":312,"name":"Yotz","market_cap":"$1.12B","price":"$3722.98","today":15,"country":"Afghanistan"},
      {"id":313,"name":"Devshare","market_cap":"$4.27B","price":"$7199.53","today":74,"country":"Afghanistan"},
      {"id":314,"name":"Yotz","market_cap":"$893.84M","price":"$5057.26","today":10,"country":"Afghanistan"},
      {"id":315,"name":"Izio","market_cap":"$1.94B","price":"$4006.58","today":99,"country":"Afghanistan"},
      {"id":316,"name":"Jabbersphere","market_cap":"$150.62M","price":"$6672.00","today":68,"country":"Afghanistan"},
      {"id":317,"name":"Realpoint","market_cap":"$5.43B","price":"$6466.69","today":75,"country":"Afghanistan"},
      {"id":318,"name":"Topdrive","market_cap":"n/a","price":"$1468.49","today":39,"country":"Afghanistan"},
      {"id":319,"name":"Minyx","market_cap":"n/a","price":"$9505.79","today":97,"country":"Afghanistan"},
      {"id":320,"name":"Tagfeed","market_cap":"$5.65B","price":"$7788.54","today":6,"country":"Afghanistan"},
      {"id":321,"name":"Avamm","market_cap":"$914.46M","price":"$8380.97","today":3,"country":"Afghanistan"},
      {"id":322,"name":"Vidoo","market_cap":"$340.68M","price":"$1965.66","today":32,"country":"Afghanistan"},
      {"id":323,"name":"Skibox","market_cap":"n/a","price":"$8854.12","today":36,"country":"Afghanistan"},
      {"id":324,"name":"Twitternation","market_cap":"$12.86B","price":"$3574.43","today":67,"country":"Afghanistan"},
      {"id":325,"name":"Blogspan","market_cap":"$276.59M","price":"$5490.25","today":9,"country":"Afghanistan"},
      {"id":326,"name":"Myworks","market_cap":"$192.23M","price":"$5413.75","today":37,"country":"Afghanistan"},
      {"id":327,"name":"Chatterbridge","market_cap":"$273.46M","price":"$2448.17","today":22,"country":"Afghanistan"},
      {"id":328,"name":"Skipstorm","market_cap":"$10.76B","price":"$3729.19","today":75,"country":"Afghanistan"},
      {"id":329,"name":"Ozu","market_cap":"$30.67B","price":"$5816.07","today":33,"country":"Afghanistan"},
      {"id":330,"name":"Oloo","market_cap":"$520.56M","price":"$3397.21","today":81,"country":"Afghanistan"},
      {"id":331,"name":"Zoomdog","market_cap":"$3.6B","price":"$5400.79","today":86,"country":"Afghanistan"},
      {"id":332,"name":"Edgeify","market_cap":"n/a","price":"$4969.30","today":59,"country":"Afghanistan"},
      {"id":333,"name":"Twitterbridge","market_cap":"$240.93M","price":"$4252.46","today":17,"country":"Afghanistan"},
      {"id":334,"name":"Zazio","market_cap":"$67.87M","price":"$1515.42","today":52,"country":"Afghanistan"},
      {"id":335,"name":"Eayo","market_cap":"n/a","price":"$8629.42","today":83,"country":"Afghanistan"},
      {"id":336,"name":"Eare","market_cap":"n/a","price":"$5210.44","today":72,"country":"Afghanistan"},
      {"id":337,"name":"Roomm","market_cap":"$14.44B","price":"$1681.99","today":63,"country":"Afghanistan"},
      {"id":338,"name":"Fivespan","market_cap":"$161.77M","price":"$5895.62","today":35,"country":"Afghanistan"},
      {"id":339,"name":"Skivee","market_cap":"$4.13B","price":"$1205.62","today":97,"country":"Afghanistan"},
      {"id":340,"name":"Yacero","market_cap":"$19.95B","price":"$7703.55","today":3,"country":"Afghanistan"},
      {"id":341,"name":"Brainlounge","market_cap":"$401.18M","price":"$9276.98","today":22,"country":"Afghanistan"},
      {"id":342,"name":"Skipstorm","market_cap":"$285.58M","price":"$6954.27","today":31,"country":"Afghanistan"},
      {"id":343,"name":"Yombu","market_cap":"$220.34M","price":"$9940.95","today":10,"country":"Afghanistan"},
      {"id":344,"name":"Twinte","market_cap":"$125.47M","price":"$2139.17","today":79,"country":"Afghanistan"},
      {"id":345,"name":"Abatz","market_cap":"$10.31M","price":"$8634.85","today":93,"country":"Afghanistan"},
      {"id":346,"name":"Photojam","market_cap":"$9.66B","price":"$5693.11","today":77,"country":"Afghanistan"},
      {"id":347,"name":"Eare","market_cap":"$440.65M","price":"$3231.75","today":55,"country":"Afghanistan"},
      {"id":348,"name":"Viva","market_cap":"$3.66B","price":"$6620.90","today":44,"country":"Afghanistan"},
      {"id":349,"name":"Skalith","market_cap":"$346.48M","price":"$4912.22","today":59,"country":"Afghanistan"},
      {"id":350,"name":"Skilith","market_cap":"$23.91B","price":"$5936.40","today":1,"country":"Afghanistan"},
      {"id":351,"name":"InnoZ","market_cap":"$43.94M","price":"$3353.99","today":38,"country":"Afghanistan"},
      {"id":352,"name":"Photospace","market_cap":"$14.95M","price":"$3886.42","today":62,"country":"Afghanistan"},
      {"id":353,"name":"Rhybox","market_cap":"$27.59M","price":"$2573.29","today":81,"country":"Afghanistan"},
      {"id":354,"name":"Lazzy","market_cap":"$2.6B","price":"$221.83","today":88,"country":"Afghanistan"},
      {"id":355,"name":"Twinder","market_cap":"$50.45M","price":"$9637.98","today":41,"country":"Afghanistan"},
      {"id":356,"name":"Rooxo","market_cap":"n/a","price":"$6220.34","today":8,"country":"Afghanistan"},
      {"id":357,"name":"Myworks","market_cap":"$400.4M","price":"$4824.73","today":46,"country":"Afghanistan"},
      {"id":358,"name":"Twinte","market_cap":"$788.64M","price":"$1748.14","today":88,"country":"Afghanistan"},
      {"id":359,"name":"Zoonoodle","market_cap":"$1.9B","price":"$3410.75","today":61,"country":"Afghanistan"},
      {"id":360,"name":"Yata","market_cap":"n/a","price":"$4642.36","today":92,"country":"Afghanistan"},
      {"id":361,"name":"Flipstorm","market_cap":"$184.1M","price":"$225.82","today":89,"country":"Afghanistan"},
      {"id":362,"name":"Quatz","market_cap":"$45.41M","price":"$7195.83","today":83,"country":"Afghanistan"},
      {"id":363,"name":"Dabtype","market_cap":"$29.39M","price":"$9117.28","today":6,"country":"Afghanistan"},
      {"id":364,"name":"Yata","market_cap":"$671.8M","price":"$4158.74","today":23,"country":"Afghanistan"},
      {"id":365,"name":"Babbleblab","market_cap":"$88.58B","price":"$9857.75","today":91,"country":"Afghanistan"},
      {"id":366,"name":"Realpoint","market_cap":"$179.44M","price":"$551.75","today":6,"country":"Afghanistan"},
      {"id":367,"name":"Divavu","market_cap":"$595.41M","price":"$2335.76","today":83,"country":"Afghanistan"},
      {"id":368,"name":"Mudo","market_cap":"$2.35B","price":"$523.91","today":74,"country":"Afghanistan"},
      {"id":369,"name":"Quinu","market_cap":"$896.34M","price":"$8234.59","today":91,"country":"Afghanistan"},
      {"id":370,"name":"Tavu","market_cap":"$703.55M","price":"$1193.59","today":5,"country":"Afghanistan"},
      {"id":371,"name":"Jabbersphere","market_cap":"n/a","price":"$8232.94","today":64,"country":"Afghanistan"},
      {"id":372,"name":"Mydeo","market_cap":"$81.78B","price":"$1324.06","today":65,"country":"Afghanistan"},
      {"id":373,"name":"Demimbu","market_cap":"$979.59M","price":"$7240.49","today":35,"country":"Afghanistan"},
      {"id":374,"name":"Voolith","market_cap":"$24.17B","price":"$5716.92","today":40,"country":"Afghanistan"},
      {"id":375,"name":"Divanoodle","market_cap":"$249.26M","price":"$936.77","today":5,"country":"Afghanistan"},
      {"id":376,"name":"Pixonyx","market_cap":"$700.65M","price":"$5371.80","today":39,"country":"Afghanistan"},
      {"id":377,"name":"Zoombeat","market_cap":"$92.4M","price":"$4801.62","today":71,"country":"Afghanistan"},
      {"id":378,"name":"Skaboo","market_cap":"n/a","price":"$238.27","today":22,"country":"Afghanistan"},
      {"id":379,"name":"Feedmix","market_cap":"$8.56B","price":"$130.78","today":57,"country":"Afghanistan"},
      {"id":380,"name":"Digitube","market_cap":"$56.73M","price":"$9207.01","today":72,"country":"Afghanistan"},
      {"id":381,"name":"Gabcube","market_cap":"n/a","price":"$7943.92","today":82,"country":"Afghanistan"},
      {"id":382,"name":"Roombo","market_cap":"$8.67M","price":"$7307.42","today":71,"country":"Afghanistan"},
      {"id":383,"name":"DabZ","market_cap":"$25.39M","price":"$5525.33","today":3,"country":"Afghanistan"},
      {"id":384,"name":"Flipstorm","market_cap":"$475.85M","price":"$7761.35","today":69,"country":"Afghanistan"},
      {"id":385,"name":"Meedoo","market_cap":"$1.64B","price":"$3617.62","today":74,"country":"Afghanistan"},
      {"id":386,"name":"LiveZ","market_cap":"$123.47M","price":"$2041.31","today":17,"country":"Afghanistan"},
      {"id":387,"name":"Livetube","market_cap":"n/a","price":"$9319.69","today":48,"country":"Afghanistan"},
      {"id":388,"name":"Reallinks","market_cap":"$519.03M","price":"$3157.40","today":30,"country":"Afghanistan"},
      {"id":389,"name":"Voonte","market_cap":"$5.04B","price":"$5942.87","today":46,"country":"Afghanistan"},
      {"id":390,"name":"Wordpedia","market_cap":"$2.88B","price":"$899.96","today":24,"country":"Afghanistan"},
      {"id":391,"name":"Photobug","market_cap":"$324.79M","price":"$3249.24","today":41,"country":"Afghanistan"},
      {"id":392,"name":"Skyble","market_cap":"$54.39M","price":"$3131.45","today":89,"country":"Afghanistan"},
      {"id":393,"name":"Bluezoom","market_cap":"$95.35M","price":"$3236.23","today":79,"country":"Afghanistan"},
      {"id":394,"name":"Gigabox","market_cap":"$1.36B","price":"$8018.81","today":81,"country":"Afghanistan"},
      {"id":395,"name":"Edgepulse","market_cap":"$196.97M","price":"$7736.76","today":96,"country":"Afghanistan"},
      {"id":396,"name":"Edgeblab","market_cap":"$24.03B","price":"$6339.51","today":60,"country":"Afghanistan"},
      {"id":397,"name":"Browsecat","market_cap":"$580.2M","price":"$6043.22","today":90,"country":"Afghanistan"},
      {"id":398,"name":"Brainbox","market_cap":"$229.56M","price":"$6761.01","today":9,"country":"Afghanistan"},
      {"id":399,"name":"Oyondu","market_cap":"$60.41M","price":"$5538.43","today":50,"country":"Afghanistan"},
      {"id":400,"name":"Blogpad","market_cap":"$532.8M","price":"$170.26","today":67,"country":"Afghanistan"},
      {"id":401,"name":"Babbleset","market_cap":"$56.28B","price":"$4587.78","today":66,"country":"Afghanistan"},
      {"id":402,"name":"Bubblebox","market_cap":"$260.75M","price":"$5998.62","today":63,"country":"Afghanistan"},
      {"id":403,"name":"Bluejam","market_cap":"$1.04B","price":"$2533.97","today":49,"country":"Afghanistan"},
      {"id":404,"name":"Yoveo","market_cap":"n/a","price":"$8034.23","today":91,"country":"Afghanistan"},
      {"id":405,"name":"Eare","market_cap":"$575.53M","price":"$7774.70","today":7,"country":"Afghanistan"},
      {"id":406,"name":"Katz","market_cap":"$181.24M","price":"$8363.20","today":12,"country":"Afghanistan"},
      {"id":407,"name":"Feedbug","market_cap":"$727.12M","price":"$8610.47","today":5,"country":"Afghanistan"},
      {"id":408,"name":"Linkbuzz","market_cap":"$514.79M","price":"$4240.67","today":54,"country":"Afghanistan"},
      {"id":409,"name":"Blogtags","market_cap":"$4.16B","price":"$245.78","today":85,"country":"Afghanistan"},
      {"id":410,"name":"Babbleset","market_cap":"$112.63M","price":"$9803.35","today":96,"country":"Afghanistan"},
      {"id":411,"name":"Quimm","market_cap":"$641.08M","price":"$8657.27","today":9,"country":"Afghanistan"},
      {"id":412,"name":"Camido","market_cap":"$25.18B","price":"$662.16","today":100,"country":"Afghanistan"},
      {"id":413,"name":"Thoughtworks","market_cap":"$56.32M","price":"$8453.36","today":74,"country":"Afghanistan"},
      {"id":414,"name":"Twitternation","market_cap":"$349.29M","price":"$1906.76","today":25,"country":"Afghanistan"},
      {"id":415,"name":"Mydo","market_cap":"n/a","price":"$175.87","today":91,"country":"Afghanistan"},
      {"id":416,"name":"Yotz","market_cap":"$7.22B","price":"$5910.81","today":34,"country":"Afghanistan"},
      {"id":417,"name":"Voolia","market_cap":"$26.98B","price":"$4968.27","today":53,"country":"Afghanistan"},
      {"id":418,"name":"Blogpad","market_cap":"$4.13B","price":"$512.94","today":32,"country":"Afghanistan"},
      {"id":419,"name":"Twitterbridge","market_cap":"$375.08M","price":"$4207.45","today":51,"country":"Afghanistan"},
      {"id":420,"name":"Dazzlesphere","market_cap":"$929.63M","price":"$4867.17","today":28,"country":"Afghanistan"},
      {"id":421,"name":"Photobug","market_cap":"$3.33B","price":"$2917.29","today":63,"country":"Afghanistan"},
      {"id":422,"name":"Wikizz","market_cap":"$4.14B","price":"$6826.06","today":20,"country":"Afghanistan"},
      {"id":423,"name":"Tagpad","market_cap":"n/a","price":"$9423.63","today":60,"country":"Afghanistan"},
      {"id":424,"name":"Zoomcast","market_cap":"$86.02M","price":"$3681.51","today":22,"country":"Afghanistan"},
      {"id":425,"name":"Skyba","market_cap":"$164.46M","price":"$7865.65","today":81,"country":"Afghanistan"},
      {"id":426,"name":"Agimba","market_cap":"$980.54M","price":"$3731.73","today":40,"country":"Afghanistan"},
      {"id":427,"name":"Zava","market_cap":"$4.38B","price":"$6721.57","today":75,"country":"Afghanistan"},
      {"id":428,"name":"Ntags","market_cap":"$2.85B","price":"$5879.38","today":39,"country":"Afghanistan"},
      {"id":429,"name":"Kwideo","market_cap":"$128.5M","price":"$7515.38","today":12,"country":"Afghanistan"},
      {"id":430,"name":"Bluejam","market_cap":"$82.81M","price":"$8570.72","today":31,"country":"Afghanistan"},
      {"id":431,"name":"Zoomcast","market_cap":"$38.42B","price":"$5910.27","today":38,"country":"Afghanistan"},
      {"id":432,"name":"Avaveo","market_cap":"$38.48B","price":"$7526.36","today":14,"country":"Afghanistan"},
      {"id":433,"name":"Voonix","market_cap":"$1.48B","price":"$9898.49","today":4,"country":"Afghanistan"},
      {"id":434,"name":"Flashdog","market_cap":"$269.31B","price":"$8864.38","today":68,"country":"Afghanistan"},
      {"id":435,"name":"Linkbridge","market_cap":"$11.48B","price":"$9117.21","today":9,"country":"Afghanistan"},
      {"id":436,"name":"Janyx","market_cap":"$9.73M","price":"$7374.52","today":45,"country":"Afghanistan"},
      {"id":437,"name":"Avamm","market_cap":"$498.57M","price":"$8067.69","today":21,"country":"Afghanistan"},
      {"id":438,"name":"Meeveo","market_cap":"$159.61M","price":"$5211.67","today":67,"country":"Afghanistan"},
      {"id":439,"name":"Gabvine","market_cap":"$2B","price":"$148.27","today":21,"country":"Afghanistan"},
      {"id":440,"name":"Babbleopia","market_cap":"$6.43B","price":"$9804.69","today":44,"country":"Afghanistan"},
      {"id":441,"name":"Digitube","market_cap":"$6.96B","price":"$5362.64","today":77,"country":"Afghanistan"},
      {"id":442,"name":"Flashdog","market_cap":"$888.93M","price":"$7784.01","today":16,"country":"Afghanistan"},
      {"id":443,"name":"Mydeo","market_cap":"$16.06B","price":"$3934.31","today":86,"country":"Afghanistan"},
      {"id":444,"name":"Twitterlist","market_cap":"n/a","price":"$5426.09","today":29,"country":"Afghanistan"},
      {"id":445,"name":"Voolith","market_cap":"$741.77B","price":"$4666.55","today":3,"country":"Afghanistan"},
      {"id":446,"name":"Jaxbean","market_cap":"$79.44B","price":"$9744.53","today":13,"country":"Afghanistan"},
      {"id":447,"name":"Browsetype","market_cap":"$1.44B","price":"$4653.72","today":19,"country":"Afghanistan"},
      {"id":448,"name":"Edgeclub","market_cap":"$1.97M","price":"$9624.12","today":97,"country":"Afghanistan"},
      {"id":449,"name":"Ailane","market_cap":"$813.95M","price":"$1210.71","today":67,"country":"Afghanistan"},
      {"id":450,"name":"Skinder","market_cap":"$8.61M","price":"$8110.65","today":60,"country":"Afghanistan"},
      {"id":451,"name":"Mydeo","market_cap":"$47.9B","price":"$3313.47","today":65,"country":"Afghanistan"},
      {"id":452,"name":"Eare","market_cap":"$9.62M","price":"$1372.16","today":2,"country":"Afghanistan"},
      {"id":453,"name":"Realblab","market_cap":"$49.09M","price":"$541.15","today":20,"country":"Afghanistan"},
      {"id":454,"name":"Camimbo","market_cap":"$803.3M","price":"$5306.86","today":32,"country":"Afghanistan"},
      {"id":455,"name":"Ailane","market_cap":"$1.21B","price":"$750.93","today":7,"country":"Afghanistan"},
      {"id":456,"name":"Quimba","market_cap":"$478.88M","price":"$5411.59","today":83,"country":"Afghanistan"},
      {"id":457,"name":"Thoughtworks","market_cap":"$84.95M","price":"$9034.66","today":1,"country":"Afghanistan"},
      {"id":458,"name":"Kazu","market_cap":"$18.36B","price":"$5189.38","today":98,"country":"Afghanistan"},
      {"id":459,"name":"Browseblab","market_cap":"n/a","price":"$524.70","today":35,"country":"Afghanistan"},
      {"id":460,"name":"Jetwire","market_cap":"$290.46M","price":"$4330.87","today":3,"country":"Afghanistan"},
      {"id":461,"name":"Photofeed","market_cap":"$1.64B","price":"$5647.96","today":14,"country":"Afghanistan"},
      {"id":462,"name":"Twitterwire","market_cap":"$5.79M","price":"$5598.36","today":83,"country":"Afghanistan"},
      {"id":463,"name":"Myworks","market_cap":"$292.59M","price":"$2602.40","today":40,"country":"Afghanistan"},
      {"id":464,"name":"Pixoboo","market_cap":"$33.57M","price":"$5239.18","today":41,"country":"Afghanistan"},
      {"id":465,"name":"Thoughtsphere","market_cap":"$79.09B","price":"$1872.02","today":5,"country":"Afghanistan"},
      {"id":466,"name":"Rhynyx","market_cap":"$18.83M","price":"$2433.05","today":13,"country":"Afghanistan"},
      {"id":467,"name":"Yombu","market_cap":"$56.73M","price":"$7977.38","today":19,"country":"Afghanistan"},
      {"id":468,"name":"Oyoba","market_cap":"n/a","price":"$3472.55","today":86,"country":"Afghanistan"},
      {"id":469,"name":"Jabberstorm","market_cap":"$21.44M","price":"$4283.26","today":56,"country":"Afghanistan"},
      {"id":470,"name":"Realbuzz","market_cap":"$653.44M","price":"$281.25","today":25,"country":"Afghanistan"},
      {"id":471,"name":"Geba","market_cap":"$18.49M","price":"$7788.99","today":28,"country":"Afghanistan"},
      {"id":472,"name":"Photospace","market_cap":"$49.88M","price":"$5959.74","today":96,"country":"Afghanistan"},
      {"id":473,"name":"Dabshots","market_cap":"$23.91B","price":"$9012.56","today":51,"country":"Afghanistan"},
      {"id":474,"name":"Zoombeat","market_cap":"$375.06M","price":"$2274.81","today":69,"country":"Afghanistan"},
      {"id":475,"name":"Tagchat","market_cap":"$548.36M","price":"$1908.32","today":44,"country":"Afghanistan"},
      {"id":476,"name":"Thoughtbeat","market_cap":"$43.49B","price":"$4878.31","today":5,"country":"Afghanistan"},
      {"id":477,"name":"Ntag","market_cap":"$163.2M","price":"$360.93","today":96,"country":"Afghanistan"},
      {"id":478,"name":"Katz","market_cap":"$233.13M","price":"$5099.14","today":15,"country":"Afghanistan"},
      {"id":479,"name":"Gigaclub","market_cap":"$1.59B","price":"$5998.49","today":68,"country":"Afghanistan"},
      {"id":480,"name":"Wordify","market_cap":"$2.55B","price":"$3393.13","today":30,"country":"Afghanistan"},
      {"id":481,"name":"Trudeo","market_cap":"$5.29B","price":"$2454.31","today":89,"country":"Afghanistan"},
      {"id":482,"name":"DabZ","market_cap":"$41.23M","price":"$8350.82","today":34,"country":"Afghanistan"},
      {"id":483,"name":"Realcube","market_cap":"n/a","price":"$1591.50","today":66,"country":"Afghanistan"},
      {"id":484,"name":"BlogXS","market_cap":"$18.56M","price":"$4488.63","today":82,"country":"Afghanistan"},
      {"id":485,"name":"Bluejam","market_cap":"$52.53M","price":"$4544.73","today":63,"country":"Afghanistan"},
      {"id":486,"name":"Fliptune","market_cap":"$1.17B","price":"$5890.83","today":61,"country":"Afghanistan"},
      {"id":487,"name":"Tambee","market_cap":"$1.15B","price":"$1293.43","today":47,"country":"Afghanistan"},
      {"id":488,"name":"Shuffledrive","market_cap":"$239.77M","price":"$949.52","today":8,"country":"Afghanistan"},
      {"id":489,"name":"Tagopia","market_cap":"$403.79M","price":"$2724.10","today":98,"country":"Afghanistan"},
      {"id":490,"name":"Gigashots","market_cap":"$654.76M","price":"$6910.69","today":58,"country":"Afghanistan"},
      {"id":491,"name":"Einti","market_cap":"$1.69B","price":"$471.63","today":60,"country":"Afghanistan"},
      {"id":492,"name":"Kazu","market_cap":"$83.04M","price":"$199.04","today":37,"country":"Afghanistan"},
      {"id":493,"name":"Aivee","market_cap":"$1.8B","price":"$5654.09","today":13,"country":"Afghanistan"},
      {"id":494,"name":"Jabberbean","market_cap":"$1.28B","price":"$9547.72","today":47,"country":"Afghanistan"},
      {"id":495,"name":"Skippad","market_cap":"$674.56M","price":"$3600.66","today":49,"country":"Afghanistan"},
      {"id":496,"name":"Realfire","market_cap":"$195.15M","price":"$1116.95","today":78,"country":"Afghanistan"},
      {"id":497,"name":"Mynte","market_cap":"$522.68M","price":"$8600.58","today":65,"country":"Afghanistan"},
      {"id":498,"name":"Edgeclub","market_cap":"$41.23M","price":"$6390.12","today":6,"country":"Afghanistan"},
      {"id":499,"name":"Camido","market_cap":"n/a","price":"$640.34","today":70,"country":"Afghanistan"},
      {"id":500,"name":"Centizu","market_cap":"$38.48B","price":"$9901.50","today":93,"country":"Afghanistan"}
  ];
  

const countries = [
    // America
    { label: 'United States', value: 'us', marketCap: '$59.865 T', companies: 3712, region: 'America' },
    { label: 'Canada', value: 'ca', marketCap: '$3.011 T', companies: 472, region: 'America' },
    { label: 'Brazil', value: 'br', marketCap: '$783.95 B', companies: 84, region: 'America' },
    { label: 'Mexico', value: 'mx', marketCap: '$515.08 B', companies: 31, region: 'America' },
    { label: 'Chile', value: 'cl', marketCap: '$113.61 B', companies: 21, region: 'America' },
  
    // Asia
    { label: 'China', value: 'cn', marketCap: '$7.219 T', companies: 319, region: 'Asia' },
    { label: 'Japan', value: 'jp', marketCap: '$4.810 T', companies: 350, region: 'Asia' },
    { label: 'India', value: 'in', marketCap: '$4.643 T', companies: 587, region: 'Asia' },
    { label: 'Taiwan', value: 'tw', marketCap: '$1.965 T', companies: 101, region: 'Asia' },
    { label: 'South Korea', value: 'kr', marketCap: '$1.166 T', companies: 104, region: 'Asia' },
    { label: 'Hong Kong', value: 'hk', marketCap: '$944.68 B', companies: 148, region: 'Asia' },
    { label: 'Singapore', value: 'sg', marketCap: '$532.73 B', companies: 77, region: 'Asia' },
    { label: 'Indonesia', value: 'id', marketCap: '$440.17 B', companies: 47, region: 'Asia' },
    { label: 'Thailand', value: 'th', marketCap: '$425.22 B', companies: 59, region: 'Asia' },
    { label: 'Malaysia', value: 'my', marketCap: '$280.78 B', companies: 49, region: 'Asia' },
    { label: 'Vietnam', value: 'vn', marketCap: '$122.35 B', companies: 37, region: 'Asia' },
    { label: 'Philippines', value: 'ph', marketCap: '$138.82 B', companies: 14, region: 'Asia' },
    { label: 'Pakistan', value: 'pk', marketCap: '$26.77 B', companies: 38, region: 'Asia' },
    { label: 'Cambodia', value: 'kh', marketCap: '$4.62 B', companies: 9, region: 'Asia' },
  
    // Europe
    { label: 'United Kingdom', value: 'uk', marketCap: '$3.716 T', companies: 417, region: 'Europe' },
    { label: 'Germany', value: 'de', marketCap: '$2.464 T', companies: 380, region: 'Europe' },
    { label: 'France', value: 'fr', marketCap: '$2.954 T', companies: 312, region: 'Europe' },
    { label: 'Switzerland', value: 'ch', marketCap: '$2.498 T', companies: 196, region: 'Europe' },
    { label: 'Netherlands', value: 'nl', marketCap: '$1.278 T', companies: 65, region: 'Europe' },
    { label: 'Ireland', value: 'ie', marketCap: '$1.104 T', companies: 45, region: 'Europe' },
    { label: 'Sweden', value: 'se', marketCap: '$1.067 T', companies: 195, region: 'Europe' },
    { label: 'Denmark', value: 'dk', marketCap: '$911.41 B', companies: 61, region: 'Europe' },
    { label: 'Spain', value: 'es', marketCap: '$886.39 B', companies: 99, region: 'Europe' },
    { label: 'Italy', value: 'it', marketCap: '$851.18 B', companies: 132, region: 'Europe' },
    { label: 'Belgium', value: 'be', marketCap: '$353.36 B', companies: 75, region: 'Europe' },
    { label: 'Russia', value: 'ru', marketCap: '$317.30 B', companies: 17, region: 'Europe' },
    { label: 'Norway', value: 'no', marketCap: '$309.09 B', companies: 106, region: 'Europe' },
    { label: 'Finland', value: 'fi', marketCap: '$287.08 B', companies: 70, region: 'Europe' },
    { label: 'Poland', value: 'pl', marketCap: '$171.79 B', companies: 108, region: 'Europe' },
    { label: 'Austria', value: 'at', marketCap: '$159.92 B', companies: 60, region: 'Europe' },
    { label: 'Luxembourg', value: 'lu', marketCap: '$134.33 B', companies: 32, region: 'Europe' },
    { label: 'Greece', value: 'gr', marketCap: '$81.36 B', companies: 42, region: 'Europe' },
    { label: 'Portugal', value: 'pt', marketCap: '$68.91 B', companies: 17, region: 'Europe' },
    { label: 'Czech Republic', value: 'cz', marketCap: '$30.94 B', companies: 4, region: 'Europe' },
    
    // Middle East
    { label: 'Saudi Arabia', value: 'sa', marketCap: '$2.647 T', companies: 226, region: 'Middle East' },
    { label: 'United Arab Emirates', value: 'ae', marketCap: '$962.15 B', companies: 142, region: 'Middle East' },
    { label: 'Qatar', value: 'qa', marketCap: '$173.52 B', companies: 53, region: 'Middle East' },
    { label: 'Kuwait', value: 'kw', marketCap: '$130.74 B', companies: 73, region: 'Middle East' },
    { label: 'Turkey', value: 'tr', marketCap: '$206.89 B', companies: 42, region: 'Middle East' },
    { label: 'Bahrain', value: 'bh', marketCap: '$31.41 B', companies: 28, region: 'Middle East' },
    { label: 'Oman', value: 'om', marketCap: '$23.36 B', companies: 46, region: 'Middle East' },
  
    // Africa
    { label: 'South Africa', value: 'za', marketCap: '$296.80 B', companies: 49, region: 'Africa' },
  
    // Oceania
    { label: 'Australia', value: 'au', marketCap: '$1.744 T', companies: 344, region: 'Oceania' },
    { label: 'New Zealand', value: 'nz', marketCap: '$108.42 B', companies: 37, region: 'Oceania' },
    { label: 'Iceland', value: 'is', marketCap: '$21.27 B', companies: 31, region: 'Oceania' },
  ];
  

const industries = [
  { label: "Information Technology", value: "it", description: "Information Technology (IT)" },
  { label: "Agriculture", value: "agriculture", description: "Agriculture and Farming" },
  { label: "Automotive", value: "automotive", description: "Automotive Industry" },
  { label: "Aerospace", value: "aerospace", description: "Aerospace and Aviation" },
  { label: "Banking", value: "banking", description: "Banking and Financial Services" },
  { label: "Construction", value: "construction", description: "Construction and Building" },
  { label: "Education", value: "education", description: "Education and Training" },
  { label: "Energy", value: "energy", description: "Energy and Utilities" },
  { label: "Entertainment", value: "entertainment", description: "Entertainment and Media" },
  { label: "Food and Beverage", value: "food-beverage", description: "Food and Beverage Industry" },
  { label: "Healthcare", value: "healthcare", description: "Healthcare and Medical" },
  { label: "Hospitality", value: "hospitality", description: "Hospitality and Tourism" },
  { label: "Insurance", value: "insurance", description: "Insurance Industry" },
  { label: "Manufacturing", value: "manufacturing", description: "Manufacturing and Production" },
  { label: "Mining", value: "mining", description: "Mining and Metals" },
  { label: "Pharmaceutical", value: "pharmaceutical", description: "Pharmaceuticals" },
  { label: "Real Estate", value: "real-estate", description: "Real Estate and Property" },
  { label: "Retail", value: "retail", description: "Retail and Wholesale" },
  { label: "Telecommunications", value: "telecommunications", description: "Telecommunications" },
  { label: "Transportation", value: "transportation", description: "Transportation and Logistics" },
  { label: "Utilities", value: "utilities", description: "Utilities and Energy" },
  { label: "E-Commerce", value: "e-commerce", description: "E-Commerce" },
  { label: "Software", value: "software", description: "Software Development and IT" },
  { label: "Consulting", value: "consulting", description: "Consulting Services" },
  { label: "Legal", value: "legal", description: "Legal and Law Firms" },
  { label: "Media", value: "media", description: "Media and Press" },
  { label: "Textile", value: "textile", description: "Textile and Apparel" },
  { label: "Tobacco", value: "tobacco", description: "Tobacco Industry" },
  { label: "Oil and Gas", value: "oil-gas", description: "Oil and Gas Industry" },
  { label: "Chemicals", value: "chemicals", description: "Chemical Industry" },
  { label: "Semiconductors", value: "semiconductors", description: "Semiconductor Industry" },
  { label: "Defense", value: "defense", description: "Defense and Military" },
  { label: "Non-Profit", value: "non-profit", description: "Non-Profit Organizations" },
  { label: "Financial Services", value: "financial-services", description: "Financial Services Industry" },
  { label: "Logistics", value: "logistics", description: "Logistics and Supply Chain" },
  { label: "Biotechnology", value: "biotechnology", description: "Biotechnology Industry" },
  { label: "Venture Capital", value: "venture-capital", description: "Venture Capital and Investments" },
  { label: "Fashion", value: "fashion", description: "Fashion and Apparel" },
  { label: "Publishing", value: "publishing", description: "Publishing and Print Media" },
  { label: "Music", value: "music", description: "Music Industry" },
  { label: "Film", value: "film", description: "Film and Production" },
  { label: "AI", value: "ai", description: "Artificial Intelligence Industry" },
  { label: "Blockchain", value: "blockchain", description: "Blockchain and Cryptocurrency" },
  { label: "Human Resources", value: "human-resources", description: "Human Resources and Recruitment" }
];

export const companies = [
  { label: "Information Technology", value: "it", description: "Information Technology (IT)" },
  { label: "Agriculture", value: "agriculture", description: "Agriculture and Farming" },
  { label: "Automotive", value: "automotive", description: "Automotive Industry" },
  { label: "Aerospace", value: "aerospace", description: "Aerospace and Aviation" },
  { label: "Banking", value: "banking", description: "Banking and Financial Services" },
  { label: "Construction", value: "construction", description: "Construction and Building" },
  { label: "Education", value: "education", description: "Education and Training" },
  { label: "Energy", value: "energy", description: "Energy and Utilities" },
  { label: "Entertainment", value: "entertainment", description: "Entertainment and Media" },
  { label: "Food and Beverage", value: "food-beverage", description: "Food and Beverage Industry" },
  { label: "Healthcare", value: "healthcare", description: "Healthcare and Medical" },
  { label: "Hospitality", value: "hospitality", description: "Hospitality and Tourism" },
  { label: "Insurance", value: "insurance", description: "Insurance Industry" },
  { label: "Manufacturing", value: "manufacturing", description: "Manufacturing and Production" },
  { label: "Mining", value: "mining", description: "Mining and Metals" },
  { label: "Pharmaceutical", value: "pharmaceutical", description: "Pharmaceuticals" },
  { label: "Real Estate", value: "real-estate", description: "Real Estate and Property" },
  { label: "Retail", value: "retail", description: "Retail and Wholesale" },
  { label: "Telecommunications", value: "telecommunications", description: "Telecommunications" },
  { label: "Transportation", value: "transportation", description: "Transportation and Logistics" },
  { label: "Utilities", value: "utilities", description: "Utilities and Energy" },
  { label: "E-Commerce", value: "e-commerce", description: "E-Commerce" },
  { label: "Software", value: "software", description: "Software Development and IT" },
  { label: "Consulting", value: "consulting", description: "Consulting Services" },
  { label: "Legal", value: "legal", description: "Legal and Law Firms" },
  { label: "Media", value: "media", description: "Media and Press" },
  { label: "Textile", value: "textile", description: "Textile and Apparel" },
  { label: "Tobacco", value: "tobacco", description: "Tobacco Industry" },
  { label: "Oil and Gas", value: "oil-gas", description: "Oil and Gas Industry" },
  { label: "Chemicals", value: "chemicals", description: "Chemical Industry" },
  { label: "Semiconductors", value: "semiconductors", description: "Semiconductor Industry" },
  { label: "Defense", value: "defense", description: "Defense and Military" },
  { label: "Non-Profit", value: "non-profit", description: "Non-Profit Organizations" },
  { label: "Financial Services", value: "financial-services", description: "Financial Services Industry" },
  { label: "Logistics", value: "logistics", description: "Logistics and Supply Chain" },
  { label: "Biotechnology", value: "biotechnology", description: "Biotechnology Industry" },
  { label: "Venture Capital", value: "venture-capital", description: "Venture Capital and Investments" },
  { label: "Fashion", value: "fashion", description: "Fashion and Apparel" },
  { label: "Publishing", value: "publishing", description: "Publishing and Print Media" },
  { label: "Music", value: "music", description: "Music Industry" },
  { label: "Film", value: "film", description: "Film and Production" },
  { label: "AI", value: "ai", description: "Artificial Intelligence Industry" },
  { label: "Blockchain", value: "blockchain", description: "Blockchain and Cryptocurrency" },
  { label: "Human Resources", value: "human-resources", description: "Human Resources and Recruitment" }
];

const categories = [
    { label: "Market Cap", value: "Market Cap", description: "Market Cap", selected: true },
    { label: "Earnings", value: "Earnings", description: "Earnings" },
    { label: "Revenue", value: "Revenue", description: "Revenue" },
    { label: "Employees", value: "Employees", description: "Employees" },
    { label: "P/E ratio", value: "P/E ratio", description: "P/E ratio" },
    { label: "Dividend %", value: "Dividend %", description: "Dividend %" },
    { label: "Market Cap gain", value: "Market Cap gain", description: "Market Cap gain" },
    { label: "Market Cap loss", value: "Market Cap loss", description: "Market Cap loss" },
    { label: "Operating Margin", value: "Operating Margin", description: "Operating Margin" },
    { label: "Cost to borrow", value: "Cost to borrow", description: "Cost to borrow" },
    { label: "Total assets", value: "Total assets", description: "Total assets" },
    { label: "Net assets", value: "Net assets", description: "Net assets" },
    { label: "Total liabilities", value: "Total liabilities", description: "Total liabilities" },
    { label: "Total debt", value: "Total debt", description: "Total debt" },
    { label: "Cash on hand", value: "Cash on hand", description: "Cash on hand" },
    { label: "P/B ratio", value: "P/B ratio", description: "P/B ratio" },
  ];

const domains = [
    { label: 'Automakers', value: 'automakers', description: 'Category for automaker companies' },
    { label: 'Airlines', value: 'airlines', description: 'Category for airline companies' },
    { label: 'Airports', value: 'airports', description: 'Category for airport services' },
    { label: 'Aircraft manufacturers', value: 'aircraft-manufacturers', description: 'Companies manufacturing aircrafts' },
    { label: 'Banks', value: 'banks', description: 'Category for banking institutions' },
    { label: 'Hotels', value: 'hotels', description: 'Category for hotel industry' },
    { label: 'Pharmaceuticals', value: 'pharmaceuticals', description: 'Category for pharmaceutical companies' },
    { label: 'E-Commerce', value: 'e-commerce', description: 'Category for e-commerce businesses' },
    { label: 'Healthcare', value: 'healthcare', description: 'Category for healthcare companies' },
    { label: 'Courier services', value: 'courier-services', description: 'Companies providing courier services' },
    { label: 'Media/Press', value: 'media-press', description: 'Category for media and press companies' },
    { label: 'Alcoholic beverages', value: 'alcoholic-beverages', description: 'Category for alcoholic beverage companies' },
    { label: 'Beverages', value: 'beverages', description: 'Category for beverage companies' },
    { label: 'Clothing', value: 'clothing', description: 'Category for clothing and apparel companies' },
    { label: 'Mining', value: 'mining', description: 'Category for mining companies' },
    { label: 'Railways', value: 'railways', description: 'Category for railway companies' },
    { label: 'Insurance', value: 'insurance', description: 'Category for insurance companies' },
    { label: 'Real estate', value: 'real-estate', description: 'Category for real estate businesses' },
    { label: 'Ports', value: 'ports', description: 'Category for port-related businesses' },
    { label: 'Professional services', value: 'professional-services', description: 'Category for professional service providers' },
    { label: 'Food', value: 'food', description: 'Category for food industry businesses' },
    { label: 'Restaurant chains', value: 'restaurant-chains', description: 'Category for chain restaurants' },
    { label: 'Software', value: 'software', description: 'Category for software companies' },
    { label: 'Semiconductors', value: 'semiconductors', description: 'Category for semiconductor manufacturers' },
    { label: 'Tobacco', value: 'tobacco', description: 'Category for tobacco companies' },
    { label: 'Financial services', value: 'financial-services', description: 'Category for financial service providers' },
    { label: 'Oil & Gas', value: 'oil-gas', description: 'Category for oil and gas companies' },
    { label: 'Electricity', value: 'electricity', description: 'Category for electricity providers' },
    { label: 'Chemicals', value: 'chemicals', description: 'Category for chemical companies' },
    { label: 'Investment', value: 'investment', description: 'Category for investment companies' },
    { label: 'Telecommunication', value: 'telecommunication', description: 'Category for telecom companies' },
    { label: 'Retail', value: 'retail', description: 'Category for retail businesses' },
    { label: 'Internet', value: 'internet', description: 'Category for internet-related businesses' },
    { label: 'Construction', value: 'construction', description: 'Category for construction companies' },
    { label: 'Video Game', value: 'video-game', description: 'Category for video game companies' },
    { label: 'Tech', value: 'tech', description: 'Category for technology companies' },
    { label: 'AI', value: 'ai', description: 'Category for artificial intelligence businesses' }
  ];

const countryCodeToName = {
  "ad": "Andorra",
  "ae": "United Arab Emirates",
  "af": "Afghanistan",
  "ag": "Antigua and Barbuda",
  "ai": "Anguilla",
  "al": "Albania",
  "am": "Armenia",
  "ao": "Angola",
  "aq": "Antarctica",
  "ar": "Argentina",
  "as": "American Samoa",
  "at": "Austria",
  "au": "Australia",
  "aw": "Aruba",
  "ax": "Åland Islands",
  "az": "Azerbaijan",
  "ba": "Bosnia and Herzegovina",
  "bb": "Barbados",
  "bd": "Bangladesh",
  "be": "Belgium",
  "bf": "Burkina Faso",
  "bg": "Bulgaria",
  "bh": "Bahrain",
  "bi": "Burundi",
  "bj": "Benin",
  "bl": "Saint Barthélemy",
  "bm": "Bermuda",
  "bn": "Brunei",
  "bo": "Bolivia",
  "bq": "Caribbean Netherlands",
  "br": "Brazil",
  "bs": "Bahamas",
  "bt": "Bhutan",
  "bv": "Bouvet Island",
  "bw": "Botswana",
  "by": "Belarus",
  "bz": "Belize",
  "ca": "Canada",
  "cc": "Cocos (Keeling) Islands",
  "cd": "DR Congo",
  "cf": "Central African Republic",
  "cg": "Republic of the Congo",
  "ch": "Switzerland",
  "ci": "Côte d'Ivoire (Ivory Coast)",
  "ck": "Cook Islands",
  "cl": "Chile",
  "cm": "Cameroon",
  "cn": "China",
  "co": "Colombia",
  "cr": "Costa Rica",
  "cu": "Cuba",
  "cv": "Cape Verde",
  "cw": "Curaçao",
  "cx": "Christmas Island",
  "cy": "Cyprus",
  "cz": "Czechia",
  "de": "Germany",
  "dj": "Djibouti",
  "dk": "Denmark",
  "dm": "Dominica",
  "do": "Dominican Republic",
  "dz": "Algeria",
  "ec": "Ecuador",
  "ee": "Estonia",
  "eg": "Egypt",
  "eh": "Western Sahara",
  "er": "Eritrea",
  "es": "Spain",
  "et": "Ethiopia",
  "eu": "European Union",
  "fi": "Finland",
  "fj": "Fiji",
  "fk": "Falkland Islands",
  "fm": "Micronesia",
  "fo": "Faroe Islands",
  "fr": "France",
  "ga": "Gabon",
  "gb": "United Kingdom",
  "gb-eng": "England",
  "gb-nir": "Northern Ireland",
  "gb-sct": "Scotland",
  "gb-wls": "Wales",
  "gd": "Grenada",
  "ge": "Georgia",
  "gf": "French Guiana",
  "gg": "Guernsey",
  "gh": "Ghana",
  "gi": "Gibraltar",
  "gl": "Greenland",
  "gm": "Gambia",
  "gn": "Guinea",
  "gp": "Guadeloupe",
  "gq": "Equatorial Guinea",
  "gr": "Greece",
  "gs": "South Georgia",
  "gt": "Guatemala",
  "gu": "Guam",
  "gw": "Guinea-Bissau",
  "gy": "Guyana",
  "hk": "Hong Kong",
  "hm": "Heard Island and McDonald Islands",
  "hn": "Honduras",
  "hr": "Croatia",
  "ht": "Haiti",
  "hu": "Hungary",
  "id": "Indonesia",
  "ie": "Ireland",
  "il": "Israel",
  "im": "Isle of Man",
  "in": "India",
  "io": "British Indian Ocean Territory",
  "iq": "Iraq",
  "ir": "Iran",
  "is": "Iceland",
  "it": "Italy",
  "je": "Jersey",
  "jm": "Jamaica",
  "jo": "Jordan",
  "jp": "Japan",
  "ke": "Kenya",
  "kg": "Kyrgyzstan",
  "kh": "Cambodia",
  "ki": "Kiribati",
  "km": "Comoros",
  "kn": "Saint Kitts and Nevis",
  "kp": "North Korea",
  "kr": "South Korea",
  "kw": "Kuwait",
  "ky": "Cayman Islands",
  "kz": "Kazakhstan",
  "la": "Laos",
  "lb": "Lebanon",
  "lc": "Saint Lucia",
  "li": "Liechtenstein",
  "lk": "Sri Lanka",
  "lr": "Liberia",
  "ls": "Lesotho",
  "lt": "Lithuania",
  "lu": "Luxembourg",
  "lv": "Latvia",
  "ly": "Libya",
  "ma": "Morocco",
  "mc": "Monaco",
  "md": "Moldova",
  "me": "Montenegro",
  "mf": "Saint Martin",
  "mg": "Madagascar",
  "mh": "Marshall Islands",
  "mk": "North Macedonia",
  "ml": "Mali",
  "mm": "Myanmar",
  "mn": "Mongolia",
  "mo": "Macau",
  "mp": "Northern Mariana Islands",
  "mq": "Martinique",
  "mr": "Mauritania",
  "ms": "Montserrat",
  "mt": "Malta",
  "mu": "Mauritius",
  "mv": "Maldives",
  "mw": "Malawi",
  "mx": "Mexico",
  "my": "Malaysia",
  "mz": "Mozambique",
  "na": "Namibia",
  "nc": "New Caledonia",
  "ne": "Niger",
  "nf": "Norfolk Island",
  "ng": "Nigeria",
  "ni": "Nicaragua",
  "nl": "Netherlands",
  "no": "Norway",
  "np": "Nepal",
  "nr": "Nauru",
  "nu": "Niue",
  "nz": "New Zealand",
  "om": "Oman",
  "pa": "Panama",
  "pe": "Peru",
  "pf": "French Polynesia",
  "pg": "Papua New Guinea",
  "ph": "Philippines",
  "pk": "Pakistan",
  "pl": "Poland",
  "pm": "Saint Pierre and Miquelon",
  "pn": "Pitcairn Islands",
  "pr": "Puerto Rico",
  "ps": "Palestine",
  "pt": "Portugal",
  "pw": "Palau",
  "py": "Paraguay",
  "qa": "Qatar",
  "re": "Réunion",
  "ro": "Romania",
  "rs": "Serbia",
  "ru": "Russia",
  "rw": "Rwanda",
  "sa": "Saudi Arabia",
  "sb": "Solomon Islands",
  "sc": "Seychelles",
  "sd": "Sudan",
  "se": "Sweden",
  "sg": "Singapore",
  "sh": "Saint Helena, Ascension and Tristan da Cunha",
  "si": "Slovenia",
  "sj": "Svalbard and Jan Mayen",
  "sk": "Slovakia",
  "sl": "Sierra Leone",
  "sm": "San Marino",
  "sn": "Senegal",
  "so": "Somalia",
  "sr": "Suriname",
  "ss": "South Sudan",
  "st": "São Tomé and Príncipe",
  "sv": "El Salvador",
  "sx": "Sint Maarten",
  "sy": "Syria",
  "sz": "Eswatini (Swaziland)",
  "tc": "Turks and Caicos Islands",
  "td": "Chad",
  "tf": "French Southern and Antarctic Lands",
  "tg": "Togo",
  "th": "Thailand",
  "tj": "Tajikistan",
  "tk": "Tokelau",
  "tl": "Timor-Leste",
  "tm": "Turkmenistan",
  "tn": "Tunisia",
  "to": "Tonga",
  "tr": "Turkey",
  "tt": "Trinidad and Tobago",
  "tv": "Tuvalu",
  "tw": "Taiwan",
  "tz": "Tanzania",
  "ua": "Ukraine",
  "ug": "Uganda",
  "um": "United States Minor Outlying Islands",
  "un": "United Nations",
  "us": "United States",
  "us-ak": "Alaska",
  "us-al": "Alabama",
  "us-ar": "Arkansas",
  "us-az": "Arizona",
  "us-ca": "California",
  "us-co": "Colorado",
  "us-ct": "Connecticut",
  "us-de": "Delaware",
  "us-fl": "Florida",
  "us-ga": "Georgia",
  "us-hi": "Hawaii",
  "us-ia": "Iowa",
  "us-id": "Idaho",
  "us-il": "Illinois",
  "us-in": "Indiana",
  "us-ks": "Kansas",
  "us-ky": "Kentucky",
  "us-la": "Louisiana",
  "us-ma": "Massachusetts",
  "us-md": "Maryland",
  "us-me": "Maine",
  "us-mi": "Michigan",
  "us-mn": "Minnesota",
  "us-mo": "Missouri",
  "us-ms": "Mississippi",
  "us-mt": "Montana",
  "us-nc": "North Carolina",
  "us-nd": "North Dakota",
  "us-ne": "Nebraska",
  "us-nh": "New Hampshire",
  "us-nj": "New Jersey",
  "us-nm": "New Mexico",
  "us-nv": "Nevada",
  "us-ny": "New York",
  "us-oh": "Ohio",
  "us-ok": "Oklahoma",
  "us-or": "Oregon",
  "us-pa": "Pennsylvania",
  "us-ri": "Rhode Island",
  "us-sc": "South Carolina",
  "us-sd": "South Dakota",
  "us-tn": "Tennessee",
  "us-tx": "Texas",
  "us-ut": "Utah",
  "us-va": "Virginia",
  "us-vt": "Vermont",
  "us-wa": "Washington",
  "us-wi": "Wisconsin",
  "us-wv": "West Virginia",
  "us-wy": "Wyoming",
  "uy": "Uruguay",
  "uz": "Uzbekistan",
  "va": "Vatican City (Holy See)",
  "vc": "Saint Vincent and the Grenadines",
  "ve": "Venezuela",
  "vg": "British Virgin Islands",
  "vi": "United States Virgin Islands",
  "vn": "Vietnam",
  "vu": "Vanuatu",
  "wf": "Wallis and Futuna",
  "ws": "Samoa",
  "xk": "Kosovo",
  "ye": "Yemen",
  "yt": "Mayotte",
  "za": "South Africa",
  "zm": "Zambia",
  "zw": "Zimbabwe"
} 

export {columns, market_caps, statusOptions, countries, industries, categories, domains, countryCodeToName};